version: 2
jobs:
  x11:
    docker:
      - image: mmatyas/pegasus-qt_x11-bionic
    environment:
      QT_VERSION: qt5156
      QT_TARGET: x11-static
      BUILDOPTS:
        USE_SDL_GAMEPAD=1
        USE_SDL_POWER=1
        INSTALL_BINDIR=/usr/bin
        INSTALL_ICONDIR=/usr/share/icons/hicolor
        INSTALL_DESKTOPDIR=/usr/share/applications
        INSTALL_APPSTREAMDIR=/usr/share/metainfo
        INSTALL_DOCDIR=/usr/share/doc/pegasus-frontend
        SDL_LIBS="-L/opt/SDL2-2.0.20/lib -lSDL2"
        SDL_INCLUDES=/opt/SDL2-2.0.20/include/SDL2
      INSTALL_BINDIR: /usr/bin/
      GEMDIR: /home/build/.gem/ruby/2.5.0/bin/
    steps:
      - run: gem install --user-install -N fpm -v 1.10.2
      - checkout
      - run: .circleci/prepare.sh
      - run: curl -L "https://github.com/mmatyas/pegasus-frontend/releases/download/alpha1/SDL2-2.0.20_x11-bionic.tar.xz" | tar xJf - -C /opt/
      - run: .circleci/build.sh
      - run: .circleci/objdump_linux.sh ''
      # Deploy
      - run: .circleci/zip_linux.sh
      - run: .circleci/stage.sh

  release:
    docker:
      - image: mmatyas/pegasus-qt_x11-bionic
    steps:
      - checkout
      - run: .circleci/release_github.sh


workflows:
  version: 2
  all:
    jobs:
      - x11
      - release:
          requires:
            - x11